/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program.pemesanan;

/**
 *
 * @author HP
 */
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Pemesanan2 extends javax.swing.JFrame {
Connection Con;
Statement State;

DefaultTableModel tableModel = new DefaultTableModel(new Object [][] {},new String[]{"Jenis Makanan","Qty","Harga","Total Harga"});

    /**
     * Creates new form Pemesanan2
     */
    public Pemesanan2() {
        initComponents();
    }
public void inisialtabel(){
    tb1Pesan.setModel(tableModel);
}
private  void noOrder() throws SQLException{
    try{
        Con = KoneksiDatabase.getKoneksi();
        State = Con.createStatement();
        String sql = "SELECT No_Order FROM headinputan";
        try (ResultSet rs = State.executeQuery(sql)) {
            int brs=0;
            while(rs.next()){
                brs = rs.getRow();
            }
            if(brs==0){
                txtorder.setText("1");
            }else{
                int nom=brs+1;
                txtorder.setText(String.valueOf(nom));
            }
        }
    } catch (SQLException e){
        System.out.println("Error :"+e);
    }
}
public void simpanDatabase() throws SQLException{
    try{
        String order=txtorder.getText();
        String meja=txtmeja.getText();
        String subtotal=txtsubtotal.getText();
        String hsql="INSERT INTO headinputan values ('"+order+"','"+meja+"','"+subtotal+"')";
        State.executeUpdate(hsql);
        for(int i=0;i<tb1Pesan.getRowCount();i++){
            String Jenis_Makanan = (String)tb1Pesan.getValueAt(i,0);
            String Jumlah=(String)tb1Pesan.getValueAt(i,1);
            String Harga=(String)tb1Pesan.getValueAt(i,2);
            String Total_Harga=(String)tb1Pesan.getValueAt(i,3);
            String isql = "INSERT INTO inputan values ('"+order+"','"+Jenis_Makanan+"','"+Jumlah+"','"+Harga+"','"+Total_Harga+"')";
            State.executeUpdate(isql); 
        }
    } catch (SQLException e){
        System.out.println("Error :"+e);
    }
}
public void hitungBayar(){
    try{
        int hitung=0;
        for(int i=0; i<tb1Pesan.getRowCount(); i++){
            String Total_Harga = (String)tb1Pesan.getValueAt(i,3);
            int iTotal_Harga = Integer.parseInt(Total_Harga);
            hitung = (hitung+iTotal_Harga);
        } txtsubtotal.setText(String.valueOf(hitung));
    } catch (Exception e){
        System.out.println("Error :"+e);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1Pesan = new javax.swing.JTable();
        cmbmakanan = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdeskripsi = new javax.swing.JTextArea();
        txtmeja = new javax.swing.JTextField();
        txtqty = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtorder = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JTextField();
        bReset = new javax.swing.JButton();
        bPesan = new javax.swing.JButton();
        bClose = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 51));
        jPanel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        tb1Pesan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb1Pesan);

        cmbmakanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-List Pilihan-", "Paket A", "Paket B", "Paket C", "Paket D" }));
        cmbmakanan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbmakananItemStateChanged(evt);
            }
        });
        cmbmakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbmakananActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Kristen ITC", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("No Order");

        txtdeskripsi.setColumns(20);
        txtdeskripsi.setForeground(new java.awt.Color(204, 0, 0));
        txtdeskripsi.setRows(5);
        jScrollPane2.setViewportView(txtdeskripsi);

        txtmeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmejaActionPerformed(evt);
            }
        });

        txtqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtyActionPerformed(evt);
            }
        });

        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Form Pemesanan Makanan");

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Jenis Makanan");

        jLabel7.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Deskripsi paket");

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("No meja");

        jLabel5.setFont(new java.awt.Font("Kristen ITC", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Jumlah");

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Harga");

        jLabel8.setFont(new java.awt.Font("Kristen ITC", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Total Pembayaran (Rp.)");

        bReset.setFont(new java.awt.Font("Kristen ITC", 1, 10)); // NOI18N
        bReset.setForeground(new java.awt.Color(255, 0, 0));
        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        bPesan.setFont(new java.awt.Font("Kristen ITC", 1, 10)); // NOI18N
        bPesan.setForeground(new java.awt.Color(255, 0, 0));
        bPesan.setText("Pesan");
        bPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPesanActionPerformed(evt);
            }
        });

        bClose.setBackground(new java.awt.Color(153, 153, 153));
        bClose.setFont(new java.awt.Font("Kristen ITC", 1, 10)); // NOI18N
        bClose.setForeground(new java.awt.Color(255, 0, 0));
        bClose.setText("Close");
        bClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCloseActionPerformed(evt);
            }
        });

        bSave.setFont(new java.awt.Font("Kristen ITC", 1, 10)); // NOI18N
        bSave.setForeground(new java.awt.Color(255, 0, 0));
        bSave.setText("SELESAI DAN SIMPAN");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        jLabel9.setText("tunjukan no Order ini untuk pembayaran!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(169, 169, 169))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbmakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmeja, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bSave)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(352, 352, 352)
                                    .addComponent(bClose, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(56, 56, 56)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtorder, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(46, 46, 46))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbmakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmeja, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bSave))
                        .addGap(77, 77, 77))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(bClose, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbmakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbmakananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbmakananActionPerformed

    private void txtmejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmejaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmejaActionPerformed

    private void bCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCloseActionPerformed
        // TODO add your handling code here:
        MenuUtama x = new MenuUtama();
        x.show();
        dispose();
    }//GEN-LAST:event_bCloseActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        // TODO add your handling code here:
   /*     cmbmakanan.setSelectedItem("-List Pilihan-");
        txtharga.setText(null);
        txtmeja.setText(null);
        txtqty.setText(null);
        txtdeskripsi.setText(null);
        txtsubtotal.setText(null);
    }//GEN-LAST:event_bResetActionPerformed
*/ try{
    String hsql = "DELETE FROM inputan";
    java.sql.Connection con =(Connection) KoneksiDatabase.getKoneksi();
    java.sql.PreparedStatement pstm = con.prepareStatement(hsql);
       pstm.execute();
       JOptionPane.showMessageDialog(null,"PESANAN DIHAPUS");
}catch (HeadlessException | SQLException e){
    System.out.println("ERROR :"+e);
}
    }
    private void bPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPesanActionPerformed
        // TODO add your handling code here:
        if(txtdeskripsi.getText().isEmpty() || txtmeja.getText().isEmpty() || txtqty.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Data belum lengkap!");
        }else{
            int v=0;
            v=JOptionPane.showConfirmDialog(null,"Anda sudah yakin dengan pesanan anda?","Warning",JOptionPane.YES_NO_OPTION);
            if(v==JOptionPane.YES_OPTION){
                try{
                    String Jenis_Makanan = cmbmakanan.getSelectedItem().toString();
                    String Jumlah = txtqty.getText();
                    String Harga = txtharga.getText();
                    int iJumlah = Integer.parseInt(Jumlah);
                    int iharga = Integer.parseInt(Harga);
                    int itotal = (iJumlah*iharga);
                    String Total_Harga = String.valueOf(itotal);
                    tableModel.addRow(new Object[]{Jenis_Makanan,Jumlah,Harga,Total_Harga});
                    inisialtabel();
                } catch (NumberFormatException e){
                    System.out.println("Error :"+e);
                }
            }
            cmbmakanan.setSelectedItem("-List Pilihan-");
            txtharga.setText(null);
            txtqty.setText(null);
            txtdeskripsi.setText(null);
        }
        hitungBayar();
    }//GEN-LAST:event_bPesanActionPerformed

    private void cmbmakananItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbmakananItemStateChanged
        // TODO add your handling code here:
        String pilih = cmbmakanan.getSelectedItem().toString();
    switch (pilih) {
        case "Paket A":
            {
                txtdeskripsi.setText("====Terdiri dari==="+"\n"+"Nasi"+"\n"+"Ayam Bakar"+"\n"+"Jus alpukat");
                int harga = 20000;
                txtharga.setText(String.valueOf(harga));
                break;
            }
        case "Paket B":
            {
                txtdeskripsi.setText("====Terdiri dari==="+"\n"+"Nasi"+"\n"+"Iga Bakar"+"\n"+"Es Campur");
                int harga = 25000;
                txtharga.setText(String.valueOf(harga));
                break;
            }
        case "Paket C":
            {
                txtdeskripsi.setText("====Terdiri dari==="+"\n"+"Nasi"+"\n"+"Ikan Bakar"+"\n"+"Es jeruk");
                int harga = 15000;
                txtharga.setText(String.valueOf(harga));
                break;
            }
        case "Paket D":
            {
                txtdeskripsi.setText("====Terdiri dari==="+"\n"+"Nasi Goreng"+"\n"+"Es Teh Manis");
                int harga = 10000;
                txtharga.setText(String.valueOf(harga));
                break;
            }
        default:
            txtdeskripsi.setText(null);
            break;
    }
    }//GEN-LAST:event_cmbmakananItemStateChanged

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaActionPerformed

    private void txtqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqtyActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Berhasil Disimpan!, Pesanan akan segera DI hantar");
    try {
        noOrder();
   
        simpanDatabase();
        hitungBayar();
        
        int maxdata = tb1Pesan.getRowCount();
        for(int i=0; i<maxdata; i++){
            String hitung = (String)tb1Pesan.getValueAt(i,3);
            int ihitung=Integer.parseInt(hitung);
        }
        String order=txtorder.getText();
        String total=txtsubtotal.getText();
        String meja=txtmeja.getText();
        
    try {
        String hsql = "INSERT INTO headinputan values"+"('"+order+"','"+meja+"','"+total+"')";
        State.executeUpdate(hsql);
    } catch(SQLException ex){
        System.out.println(("Error :"+ex));
    }
    txtmeja.setText(null);
    for(int i=0; i<tb1Pesan.getRowCount(); i++){
        tb1Pesan.removeAll();
    }
     } catch (SQLException ex) {
        Logger.getLogger(Pemesanan2.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_bSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pemesanan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pemesanan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pemesanan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pemesanan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pemesanan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClose;
    private javax.swing.JButton bPesan;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bSave;
    public javax.swing.JComboBox<String> cmbmakanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb1Pesan;
    private javax.swing.JTextArea txtdeskripsi;
    public javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtmeja;
    private javax.swing.JTextField txtorder;
    public javax.swing.JTextField txtqty;
    private javax.swing.JTextField txtsubtotal;
    // End of variables declaration//GEN-END:variables


}